import nutan from "../../assets/EB EC Images/Nutan.jpg";
import akshara from "../../assets/EB EC Images/AksharaManocha.jpeg";
import jahnvi from "../../assets/EB EC Images/JahnviRanjan.jpg"
import aakash from "../../assets/EB EC Images/AakashArora.jpg"
import naman from "../../assets/EB EC Images/NamanKumar.jpeg"
import anushka from "../../assets/EB EC Images/AnushkaSharma.jpg"
import khushi from "../../assets/EB EC Images/Khushi.jpg"
import manya from "../../assets/EB EC Images/ManyaBansal.jpg"
import rohit from "../../assets/EB EC Images/RohitArora.jpg"
import shreyaS from "../../assets/EB EC Images/ShreyaSaini.jpg"
import shreyaSi from "../../assets/EB EC Images/ShreyaSingh.jpg"
import sarthak from "../../assets/EB EC Images/SarthakSrivastava.jpg"
import shreyansh from "../../assets/EB EC Images/ShreyanshSrivastava.jpg"
import prarthana from "../../assets/EB EC Images/PrarthanaAggarwal.jpg"
import aabharan from "../../assets/EB EC Images/AabharanGupta.jpg"
import abhinav from "../../assets/EB EC Images/AbhinavJain.jpg"
import abhyuday from "../../assets/EB EC Images/AbhyudayVenkatesh.jpg"
import jini from "../../assets/EB EC Images/JiniManchanda.jpg"
import khushpreet from "../../assets/EB EC Images/KhushpreetSingh.jpg"
import rohitd from "../../assets/EB EC Images/RohitDeepchandani.jpg"
import vivek from "../../assets/EB EC Images/VivekArora.jpg"
import yashb from "../../assets/EB EC Images/YashBhargava.jpg"
import aarushi from "../../assets/Core images/AARUSHIRAWAL.jpg"
import abhivinesh from "../../assets/Core images/AbhivineshSharma.jpg"
import ajinkya from "../../assets/Core images/AjinkyaHon.jpg"
import ansh from "../../assets/Core images/AnshBajaj.jpg"
import arsh from "../../assets/Core images/ArshChatrath.jpg"
import ayush from "../../assets/Core images/AYUSHGARG.jpg"
import ayushm from "../../assets/Core images/AyushMishra.jpg"
import bhavik from "../../assets/Core images/BHAVIKJAIN.jpg"
import bhavya from "../../assets/Core images/Bhavya.jpg"
import hariyank from "../../assets/Core images/HARYIANKKUMRA.jpg"
import himanish from "../../assets/Core images/HimanishPuri.jpg"
import ishaan from "../../assets/Core images/IshaanSharma.jpg"
import ishita from "../../assets/Core images/IshitaOberoi.jpg"
import kaushik from "../../assets/Core images/KaushikArora.jpg"
import lakshita from "../../assets/Core images/LakshitaGupta.jpg"
import meenal from "../../assets/Core images/Meenal.jpg"
import pranav from "../../assets/Core images/PranavVaish.jpg"
import saarthi from "../../assets/Core images/SAARTHIARORA.jpg"
import sakshat from "../../assets/Core images/SakshatJain.jpg"
import srijapi from "../../assets/Core images/SriJapjiKaur.jpg"
import tanishq from "../../assets/Core images/TanishqSoni.jpg"
import udita from "../../assets/Core images/UditaChutani.jpg"
import vinayak from "../../assets/Core images/VINAYAKJAIN.jpg"
import yash from "../../assets/Core images/YashAgarwal.jpg"
import yashita from "../../assets/Core images/YashitaGupta.jpg"
import suman from "../../assets/president and faculty images/suman.jpg"
import rajesh from "../../assets/president and faculty images/sir.jpg"



const profile = {suman, rajesh, nutan, akshara, jahnvi, aakash, naman, anushka, khushi, manya, rohit, shreyaS, shreyaSi, sarthak, shreyansh, prarthana,aabharan,abhinav,abhyuday,khushpreet,jini,rohitd,vivek,yashb,aarushi,abhivinesh,ajinkya,ansh,arsh,ayush,ayushm,bhavik,bhavya,hariyank,himanish,ishaan,ishita,kaushik,lakshita,meenal,pranav,saarthi,sakshat,srijapi,tanishq,udita,vinayak,yash,yashita}

export default profile;